### ISSUE TITLE
Probelm of BART

### ISSUE THREAD

**Issue by zw-SIMM** [ZZHbible/T5-Bart_finetune#1]
Hi, have you tried to finetune BART in a small dataset?
The generated output by finetuned BART always misses the first token, but the generated output by finetuned T5 is correct.

**Comment by ZZHbible** [comment]
I've tried it on both BART and T5, and it works. I'm not sure how small your dataset is, but if it's very small, you might want to try using larger models like LLAMA, which could potentially yield better results.

**Comment by zw-SIMM** [comment]
> I've tried it on both BART and T5, and it works. I'm not sure how small your dataset is, but if it's very small, you might want to try using larger models like LLAMA, which could potentially yield better results.

比如说，我只用了8条数据来过拟合训练T5和BART，T5是完全全对的，但是BART生成的第一个token都遗失了。就比如说
input:     a-b-c-d-e-f-g-h-i-j-k
output:     -b-c-d-e-f-g-h-i-j-k

是不是因为bart的tokenize方式不同，导致同一套训练代码出了问题。

**Comment by ZZHbible** [comment]
你可以用bart的tokenizer encode试试，再decode看看是哪里的问题，按理说不应该的

**Comment by zw-SIMM** [comment]
> 你可以用bart的tokenizer encode试试，再decode看看是哪里的问题，按理说不应该的

用bart预测，每一个句子的第一个token都遗失了，但后面都是对的。

我刚看了下，bart tokenize生成的id默认是以0开始的，表示句子的开始```<s>```，但是lm_labels不包含这个0，会不会是右移一位对这个造成了影响。

**Comment by ZZHbible** [comment]
因为这个训练方式是自回归计算损失的，所以label是不含\<s\>的，或者你可以试试transformer.Trainer的训练方法试试

**Comment by zw-SIMM** [comment]
是啊，按理来说不该有问题的。多谢！
